# Generated by Django 5.2.3 on 2025-11-24 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foods", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FoodGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Nutrient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="ingredient",
            name="calories",
        ),
        migrations.RemoveField(
            model_name="ingredient",
            name="carbs",
        ),
        migrations.RemoveField(
            model_name="ingredient",
            name="fat",
        ),
        migrations.RemoveField(
            model_name="ingredient",
            name="protein",
        ),
        migrations.AddField(
            model_name="ingredient",
            name="food_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ingredients",
                to="foods.foodgroup",
            ),
        ),
        migrations.AddField(
            model_name="ingredient",
            name="nutrients",
            field=models.ManyToManyField(
                blank=True, related_name="ingredients", to="foods.nutrient"
            ),
        ),
    ]
