# Generated by Django 5.2.3 on 2025-11-20 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meals", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="meal",
            name="meal_type",
        ),
        migrations.AddField(
            model_name="meal",
            name="meal_time",
            field=models.CharField(
                blank=True,
                choices=[("lunch", "Lunch"), ("dinner", "Dinner"), ("snack", "Snack")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="meal",
            name="plate_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("metal_plate", "Metal Plate"),
                    ("metal_bowl", "Metal Bowl"),
                    ("ceramic_bowl", "Ceramic Bowl"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
