# Generated by Django 5.2.3 on 2025-11-20 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foods", "0001_initial"),
        ("meals", "0002_remove_meal_meal_type_meal_meal_time_meal_plate_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="meal",
            old_name="name",
            new_name="meal_description",
        ),
        migrations.AddField(
            model_name="meal",
            name="ingredients",
            field=models.ManyToManyField(
                blank=True, related_name="meals", to="foods.ingredient"
            ),
        ),
    ]
