# Generated by Django 5.2.3 on 2025-11-24 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meals", "0003_rename_name_meal_meal_description_meal_ingredients"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="meal",
            name="description",
        ),
        migrations.AddField(
            model_name="meal",
            name="day_cycle",
            field=models.CharField(
                blank=True,
                choices=[
                    ("day_1", "Day 1"),
                    ("day_2", "Day 2"),
                    ("day_3", "Day 3"),
                    ("day_4", "Day 4"),
                    ("day_5", "Day 5"),
                    ("day_6", "Day 6"),
                    ("day_7", "Day 7"),
                    ("day_8", "Day 8"),
                    ("day_9", "Day 9"),
                    ("day_10", "Day 10"),
                    ("day_11", "Day 11"),
                    ("day_12", "Day 12"),
                    ("day_13", "Day 13"),
                    ("day_14", "Day 14"),
                ],
                max_length=10,
                null=True,
            ),
        ),
    ]
