# Generated by Django 5.2.3 on 2025-11-24 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meals", "0004_remove_meal_description_meal_day_cycle"),
    ]

    operations = [
        migrations.AddField(
            model_name="meal",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="meals/"),
        ),
        migrations.AlterField(
            model_name="meal",
            name="meal_time",
            field=models.CharField(
                blank=True,
                choices=[("午餐", "Lunch"), ("晚餐", "Dinner"), ("零食", "Snack")],
                max_length=20,
                null=True,
            ),
        ),
    ]
