# Generated by Django 5.2.3 on 2025-11-24 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meals", "0005_meal_image_alter_meal_meal_time"),
        ("patients", "0006_remove_patient_dinner_meal_remove_patient_lunch_meal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meal",
            name="day_cycle",
            field=models.CharField(
                blank=True,
                choices=[
                    (1, "Day 1"),
                    (2, "Day 2"),
                    (3, "Day 3"),
                    (4, "Day 4"),
                    (5, "Day 5"),
                    (6, "Day 6"),
                    (7, "Day 7"),
                    (8, "Day 8"),
                    (9, "Day 9"),
                    (10, "Day 10"),
                    (11, "Day 11"),
                    (12, "Day 12"),
                    (13, "Day 13"),
                    (14, "Day 14"),
                ],
                max_length=10,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="MealAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "meal_type",
                    models.CharField(
                        choices=[
                            ("lunch", "Lunch"),
                            ("dinner", "Dinner"),
                            ("snack", "Snack"),
                        ],
                        max_length=10,
                    ),
                ),
                ("day_cycle", models.PositiveSmallIntegerField()),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "meal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="meals.meal",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meal_assignments",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "unique_together": {("patient", "meal_type", "day_cycle")},
            },
        ),
    ]
