# Generated by Django 5.2.3 on 2025-12-11 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meals", "0006_alter_meal_day_cycle_mealassignment"),
    ]

    operations = [
        migrations.AddField(
            model_name="meal",
            name="meal_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="meal",
            name="meal_time",
            field=models.CharField(
                blank=True,
                choices=[("午餐", "Lunch"), ("晚餐", "Dinner"), ("點心", "Snack")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="meal",
            name="plate_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("金属板", "Metal Plate"),
                    ("金属碗", "Metal Bowl"),
                    ("陶瓷碗", "Ceramic Bowl"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
