# Generated by Django 5.2.3 on 2025-12-11 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meals", "0007_meal_meal_name_alter_meal_meal_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meal",
            name="meal_description",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
