# Generated by Django 5.2.9 on 2025-12-15 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meals", "0008_alter_meal_meal_description"),
        ("patients", "0006_remove_patient_dinner_meal_remove_patient_lunch_meal"),
    ]

    operations = [
        migrations.CreateModel(
            name="FoodIntake",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weight_g",
                    models.FloatField(
                        blank=True,
                        help_text="Weight of food consumed in grams",
                        null=True,
                    ),
                ),
                (
                    "volume_ml",
                    models.FloatField(
                        blank=True,
                        help_text="Volume of food consumed in milliliters",
                        null=True,
                    ),
                ),
                ("consumed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "meal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="food_intakes",
                        to="meals.meal",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="food_intakes",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Food Intake",
                "verbose_name_plural": "Food Intakes",
                "unique_together": {("patient", "meal")},
            },
        ),
    ]
