# Generated by Django 5.2.3 on 2025-11-23 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("patients", "0005_alter_patient_activity_level"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecommendedIntake",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("daily_caloric_needs", models.FloatField()),
                ("carbohydrate", models.FloatField()),
                ("total_fiber", models.FloatField()),
                ("protein", models.FloatField()),
                ("fat", models.FloatField()),
                ("saturated_fatty_acids", models.FloatField()),
                ("trans_fatty_acids", models.FloatField()),
                ("alpha_linolenic_acid", models.FloatField()),
                ("linoleic_acid", models.FloatField()),
                ("dietary_cholesterol", models.FloatField()),
                ("total_water", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "patient",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommended_intake",
                        to="patients.patient",
                    ),
                ),
            ],
        ),
    ]
