# Generated by Django 5.2.3 on 2025-11-20 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("meals", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("age", models.PositiveIntegerField()),
                ("height_cm", models.FloatField()),
                ("weight_kg", models.FloatField()),
                ("heart_rate", models.PositiveIntegerField(blank=True, null=True)),
                ("systolic_bp", models.PositiveIntegerField(blank=True, null=True)),
                ("diastolic_bp", models.PositiveIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "dinner_meal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dinner_assigned_patients",
                        to="meals.meal",
                    ),
                ),
                (
                    "lunch_meal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lunch_assigned_patients",
                        to="meals.meal",
                    ),
                ),
            ],
        ),
    ]
