# Generated by Django 5.2.3 on 2025-11-23 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="activity_level",
            field=models.CharField(
                choices=[
                    ("inactive", "Inactive: ADLs only. Minimal activity beyond ADLs."),
                    (
                        "low_active",
                        "Low Active: ADLs plus 60-80 min of moderate activity.",
                    ),
                    (
                        "active",
                        "Active: ADLs plus 30-50 min moderate & 85 min vigorous activity.",
                    ),
                    (
                        "very_active",
                        "Very Active: ADLs plus 130 min vigorous activity.",
                    ),
                ],
                default="inactive",
                max_length=20,
            ),
        ),
    ]
