# Generated by Django 5.2.3 on 2025-11-23 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0002_patient_activity_level"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="activity_level",
            field=models.CharField(
                choices=[
                    ("inactive", "inactive"),
                    ("low_active", "low_active"),
                    ("active", "active"),
                    ("very_active", "very_active"),
                ],
                default="inactive",
                max_length=20,
            ),
        ),
    ]
