# Generated by Django 5.2.3 on 2025-11-23 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0003_alter_patient_activity_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="sex",
            field=models.CharField(
                blank=True,
                choices=[("male", "Male"), ("female", "Female")],
                max_length=10,
                null=True,
            ),
        ),
    ]
