# Generated by Django 5.2.3 on 2025-11-23 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0004_patient_sex"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="activity_level",
            field=models.CharField(
                choices=[
                    ("inactive", "Inactive"),
                    ("low_active", "Low Active"),
                    ("active", "Active"),
                    ("very_active", "Very Active"),
                ],
                default="inactive",
                max_length=20,
            ),
        ),
    ]
