# Generated by Django 5.2.3 on 2025-11-24 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0005_alter_patient_activity_level"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patient",
            name="dinner_meal",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="lunch_meal",
        ),
    ]
